service: labda-test

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  region: us-east-1
  memorySize: 1024
  timeout: 25
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - sqs:SendMessage
      - sqs:ReceiveMessage
      - sqs:DeleteMessage
      - sqs:GetQueueAttributes
    Resource: "${env:ARN_QUEUE_EMAIL}"
  - Effect: "Allow"
    Action:
      - sqs:ListQueues
    Resource: "${env:ARN_QUEUES}"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  imageResize:
    handler: handler.imageResize
    events:
      - http:
          path: /imageResize
          method: get
  pushToSqs:
    handler: sender.pushToSqs
    events:
      - http:
          path: /push-sqs
          method: get
  sendMailGun:
    handler: mailGunSender.sendMailGun
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn              
package:
      exclude:
        - node_modules/**
resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "Queue"                